@startuml
!include style.puml
Object "__cal:AppointmentCalendar__" as AppointmentCalendar MODEL_COLOR_T1 {
    - title = "Short Trip"
    - startDate = "5 May 2020"
    - endDate = "6 May 2020"
    - numDays = 2
    - budget = 500
    - exchangeRate = 2.9
}

@enduml
