@startuml
hide empty members
skinparam linetype ortho

interface ReadOnlyListManager
interface Model
interface UniqueListElement

class UniqueList<? extends UniqueListElement>
class PatientManager {
    UniqueList<Patient>
}
class AppointmentManager {
    UniqueList<Appointment>
}
class Description {
    String value
}

enum AppointmentStatus {
    DONE, MISSED, UPCOMING
}

Model <|.. ModelManager
UserPrefs <.. ModelManager
Patient <-r- ModelManager: filtered list
Appointment <-l- ModelManager: filtered list
Patient <-- Appointment: < has a list of
Appointment <-- Patient: < contains
Appointment -- Description
Appointment -- AppointmentStatus

ReadOnlyListManager <|.. PatientManager
PatientManager <.. ModelManager

UniqueListElement <|.. Patient
UniqueListElement <|.. Appointment

ReadOnlyListManager <|.. AppointmentManager
AppointmentManager <.. ModelManager

@enduml
