@startuml
!include style.puml
skinparam Class {
    BorderColor BACKGROUND_COLOR
    FontColor BACKGROUND_COLOR
    BackgroundColor MODEL_COLOR
    StereotypeFontColor BACKGROUND_COLOR
}
skinparam ArrowColor MODEL_COLOR_T3

Class HiddenOutside #FFFFFF

hide method
hide attribute

package Model <<Rectangle>> {
Interface ReadOnlyListManager<<Interface>>
Interface Model<<Interface>>
Class ModelManager
Class UserPrefs
Class PatientManager
Class AppointmentManager
Class CalendarManager
}

HiddenOutside ..> Model

Model <|.. ModelManager
ModelManager ..> UserPrefs
ModelManager ..> PatientManager
ModelManager ..> AppointmentManager
ModelManager ..> CalendarManager
AppointmentManager ..|> ReadOnlyListManager
PatientManager ..|> ReadOnlyListManager

'Patient <-r- ModelManager: filtered list
'Appointment <-l- ModelManager: filtered list
'Patient <-- Appointment: < has a list of
'Appointment <-- Patient: < contains
'Appointment -- Description
'Appointment -- AppointmentStatus

'ReadOnlyListManager <|.. PatientManager
'PatientManager <.. ModelManager
'
'UniqueListElement <|.. Patient
'UniqueListElement <|.. Appointment
'
'ReadOnlyListManager <|.. AppointmentManager
'AppointmentManager <.. ModelManager

@enduml
