@startuml
!include style.puml
skinparam Class {
    BorderColor BACKGROUND_COLOR
    FontColor BACKGROUND_COLOR
    BackgroundColor STORAGE_COLOR_T2
    StereotypeFontColor BACKGROUND_COLOR
}
skinparam ArrowColor STORAGE_COLOR_T2

hide method
hide attribute

package Storage <<Rectangle>> {
Interface Storage<<Interface>>
Interface PatientManagerStorage<<Interface>>
Interface AppointmentManagerStorage<<Interface>>
Interface UserPrefsStorage<<Interface>>
Class JsonAppointmentManagerStorage
Class JsonPatientManagerStorage
Class JsonUserPrefsStorage
Class StorageManager
}

StorageManager .up.|> Storage
PatientManagerStorage <|-- Storage
PatientManagerStorage <|.up. JsonPatientManagerStorage
AppointmentManagerStorage <|-- Storage
AppointmentManagerStorage <|.up. JsonAppointmentManagerStorage
UserPrefsStorage <|-- Storage
UserPrefsStorage <|.up. JsonUserPrefsStorage

@enduml
