@startuml
hide empty members
skinparam linetype ortho
class JsonAppointmentManagerStorage {
    FilePath path
}

class JsonPatientManagerStorage {
    FilePath path
}

class JsonUserPrefsStorage {
    FilePath path
}

interface PatientManagerStorage
interface AppointmentManagerStorage
interface UserPrefsStorage
interface Storage

JsonAdaptedPatient .right.> JsonAdaptedTag
JsonAdaptedAppointment .left.> JsonAdaptedTag

StorageManager ..u..|> Storage
PatientManagerStorage -r[hidden]- AppointmentManagerStorage
AppointmentManagerStorage -r[hidden]- UserPrefsStorage
StorageManager .u.> AppointmentManagerStorage
StorageManager .u.> UserPrefsStorage
StorageManager .u.> PatientManagerStorage

JsonAdaptedPatient .d.> Patient
JsonAdaptedPatient <.d. JsonSerializablePatientManager
JsonAdaptedAppointment .d.> Appointment
JsonSerializableAppointmentManager .u.> JsonAdaptedAppointment

JsonPatientManagerStorage -r-> Patient
JsonPatientManagerStorage .u.> JsonSerializablePatientManager
JsonPatientManagerStorage .d.|> PatientManagerStorage

JsonAppointmentManagerStorage -u-> Appointment
JsonAppointmentManagerStorage .d.|> AppointmentManagerStorage
JsonSerializableAppointmentManager <.d. JsonAppointmentManagerStorage

JsonUserPrefsStorage -r-> UserPrefs
JsonUserPrefsStorage .d.|> UserPrefsStorage
JsonUserPrefsStorage -l[hidden]- JsonAppointmentManagerStorage

Storage -u-|> PatientManagerStorage
Storage -u-|> AppointmentManagerStorage
Storage -u-|> UserPrefsStorage

@enduml