@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

hide method
hide attribute

skinparam Class {
    BorderColor BACKGROUND_COLOR
    FontColor BACKGROUND_COLOR
    BackgroundColor UI_COLOR_T3
    StereotypeFontColor BACKGROUND_COLOR
}
skinparam ArrowColor UI_COLOR_T3

package UI <<Rectangle>> {
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class ResultDisplay
Class StatusBarFooter
Class CommandBox
Class SideTabPane
Class XYZPage
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

Ui <|.. UiManager
UiManager --> MainWindow
MainWindow *--> SideTabPane
SideTabPane --> XYZPage
MainWindow --> HelpWindow
MainWindow *--> ResultDisplay
MainWindow *--> CommandBox
MainWindow *--> StatusBarFooter

MainWindow --|> UiPart
SideTabPane --|> UiPart
HelpWindow --|> UiPart
ResultDisplay --|> UiPart
StatusBarFooter --|> UiPart
CommandBox --|> UiPart
'XYZPage -left-|> UiPart

MainWindow ---> Logic
UiManager --> Logic
XYZPage ..> Model

note bottom of XYZPage: XYZPage = PatientInfoPage, AppointmentInfoPage, \nSchedulePage, CalendarPage, InfoPage etc

@enduml
